import '../assets/styles/main.scss'

import './accordion.js'
import './burgerMenu.js'
import './header.js'
import './video.js'
import './footer.js'
import './mask.js'
import './review.js'

import './proudReviews.js'
import './teamDentists.js'
import './honors.js'
import './otherServices.js'
import './education.js'
import './certificates.js'
import './basicServices.js'
import './doctorWork.js'